## APP CONFIG
application:
  title: Registration API (PROD) =>

## SPRING CONFIG
spring:
  sql:
    init:
      mode: never

## ACTUATOR CONFIG
management:
  endpoints:
    web:
      exposure:
        include: health, info